networks:
  wordpress-network:
    name: ${PROJECT_NAME}-network
    driver: bridge
  traefik-network:
    external: true

volumes:
  wordpress-data:
  mariadb-data:

services:
  mariadb:
    image: ${WORDPRESS_MARIADB_IMAGE_TAG}
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_USER: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_ADMIN_PASSWORD}
      # Increase MySQL limits for large imports
      MARIADB_EXTRA_FLAGS: --max_allowed_packet=256M --innodb_buffer_pool_size=256M --wait_timeout=300
    networks:
      - wordpress-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  wordpress:
    image: ${WORDPRESS_IMAGE_TAG}
    volumes:
      - wordpress-data:/bitnami/wordpress
    environment:
      WORDPRESS_DATABASE_HOST: mariadb
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_BLOG_NAME: ${WORDPRESS_BLOG_NAME}
      WORDPRESS_FIRST_NAME: ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_LAST_NAME: ${WORDPRESS_ADMIN_LASTNAME}
      WORDPRESS_USERNAME: ${WORDPRESS_ADMIN_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_SMTP_HOST: ${WORDPRESS_SMTP_ADDRESS}
      WORDPRESS_SMTP_PORT: ${WORDPRESS_SMTP_PORT}
      WORDPRESS_SMTP_USER: ${WORDPRESS_SMTP_USER_NAME}
      WORDPRESS_SMTP_PASSWORD: ${WORDPRESS_SMTP_PASSWORD}
      
      # PHP Configuration for Large Uploads
      PHP_UPLOAD_MAX_FILESIZE: 512M
      PHP_POST_MAX_SIZE: 512M
      PHP_MEMORY_LIMIT: 1024M
      PHP_MAX_EXECUTION_TIME: 600
      PHP_MAX_INPUT_TIME: 600
      PHP_MAX_INPUT_VARS: 5000
      
      # WordPress Configuration with backup PHP settings
      WORDPRESS_EXTRA_WP_CONFIG_CONTENT: |
        define('FS_METHOD', 'direct');
        define('WP_MEMORY_LIMIT', '1024M');
        define('WP_MAX_MEMORY_LIMIT', '1024M');
        @ini_set('upload_max_filesize', '512M');
        @ini_set('post_max_size', '512M');
        @ini_set('memory_limit', '1024M');
        @ini_set('max_execution_time', '600');
        @ini_set('max_input_time', '600');
        @ini_set('max_input_vars', '5000');
        @ini_set('max_file_uploads', '100');
        @ini_set('allow_url_fopen', 'On');
    networks:
      - wordpress-network
      - traefik-network
    # Increase container resources
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${WORDPRESS_HOSTNAME}`, `www.${WORDPRESS_HOSTNAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}.service=${PROJECT_NAME}"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=8080"
      - "traefik.http.routers.${PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.passhostheader=true"
      - "traefik.http.routers.${PROJECT_NAME}.middlewares=compresstraefik,${PROJECT_NAME}-body-size"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      # Large body size limit (512MB) for file uploads
      - "traefik.http.middlewares.${PROJECT_NAME}-body-size.buffering.maxRequestBodyBytes=536870912"
      - "traefik.docker.network=traefik-network"
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy