version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "label-enable"
      - "--interval"
      - "3600"
      - "--cleanup"
      - "--include-stopped"
      - "--include-volumes"
      - "--run-once"