name: Deploy to VPS (Root User)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/deploy_github_actions
          chmod 600 ~/.ssh/deploy_github_actions
        shell: bash

      - name: Build Go application
        run: go build -o docker-manager main.go

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            
            # Try cloning the repository
            if [ ! -d "/${{ secrets.VPS_ROOT_DIR}}/.git" ]; then
              echo "Cloning repository..."
              # Using GIT_SSH_COMMAND to specify the identity file
              GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes" git clone ${{ secrets.SSH_REPO }} /${{ secrets.VPS_ROOT_DIR}} || {
                echo "Failed to clone repository. Ensure the deploy key is added to GitHub."
                exit 1
              }
            else
              echo "Repository exists, pulling updates..."
              cd /${{ secrets.VPS_ROOT_DIR}}
              GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes" git pull origin main || {
                echo "Failed to pull updates. Ensure the deploy key is added to GitHub."
                exit 1
              }
            fi
            
            # Copy built Go application to the repository folder
            echo "Copying Go application..."
            cp $GITHUB_WORKSPACE/docker-manager /${{ secrets.VPS_ROOT_DIR}}/
            chmod +x /${{ secrets.VPS_ROOT_DIR}}/docker-manager
            
            # Set permissions for operation scripts
            if [ -d "/${{ secrets.VPS_ROOT_DIR}}/operations" ]; then
              echo "Setting permissions for operation scripts..."
              chmod +x /${{ secrets.VPS_ROOT_DIR}}/operations/*.sh
            fi
            
            echo "Deployment completed successfully!"