name: Deploy to VPS (Root User)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          
      - name: Build Go application
        run: go build -o docker-manager main.go

      - name: Deploy via SSH
        run: |
          # First ensure the directory exists on the remote server
          ssh -p ${{ secrets.VPS_PORT }} root@${{ secrets.VPS_HOST }} "mkdir -p ${{ secrets.VPS_ROOT_DIR }}"
          
          # Then copy the Go binary
          scp -P ${{ secrets.VPS_PORT }} docker-manager root@${{ secrets.VPS_HOST }}:${{ secrets.VPS_ROOT_DIR }}/
          
          # Execute deployment commands
          ssh -p ${{ secrets.VPS_PORT }} root@${{ secrets.VPS_HOST }} "
            set -e
            
            # Try cloning the repository
            if [ ! -d \"${{ secrets.VPS_ROOT_DIR }}/.git\" ]; then
              echo \"Cloning repository...\"
              git clone ${{ secrets.SSH_REPO }} ${{ secrets.VPS_ROOT_DIR }}
            else
              echo \"Repository exists, pulling updates...\"
              cd ${{ secrets.VPS_ROOT_DIR }}
              git pull origin main
            fi
            
            # Make the Go application executable
            chmod +x ${{ secrets.VPS_ROOT_DIR }}/docker-manager
            
            # Set permissions for operation scripts
            if [ -d \"${{ secrets.VPS_ROOT_DIR }}/operations\" ]; then
              echo \"Setting permissions for operation scripts...\"
              chmod +x ${{ secrets.VPS_ROOT_DIR }}/operations/*.sh
            fi
            
            echo \"Deployment completed successfully!\"
          "