name: Deploy to VPS (Root User)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          
      - name: Build Go application
        run: go build -o docker-manager main.go

      - name: Deploy via SSH
        run: |
          # First ensure the directory exists on the remote server
          ssh -p ${{ secrets.VPS_PORT }} root@${{ secrets.VPS_HOST }} "mkdir -p ${{ secrets.VPS_ROOT_DIR }}"
          
          # Execute deployment commands for repository management
          ssh -p ${{ secrets.VPS_PORT }} root@${{ secrets.VPS_HOST }} "
            set -e
            
            # Check if directory exists but is not a git repo
            if [ -d \"${{ secrets.VPS_ROOT_DIR }}\" ] && [ ! -d \"${{ secrets.VPS_ROOT_DIR }}/.git\" ]; then
              echo \"Directory exists but is not a git repository. Initializing git...\"
              cd ${{ secrets.VPS_ROOT_DIR }}
              git init
              git remote add origin ${{ secrets.SSH_REPO }}
              git fetch
              git checkout -f -B main origin/main
            elif [ ! -d \"${{ secrets.VPS_ROOT_DIR }}\" ]; then
              echo \"Cloning repository...\"
              git clone ${{ secrets.SSH_REPO }} ${{ secrets.VPS_ROOT_DIR }}
            else
              echo \"Repository exists, pulling updates...\"
              cd ${{ secrets.VPS_ROOT_DIR }}
              git fetch
              git reset --hard origin/main
            fi
          "
          
          # Then copy the Go binary
          scp -P ${{ secrets.VPS_PORT }} docker-manager root@${{ secrets.VPS_HOST }}:${{ secrets.VPS_ROOT_DIR }}/
          
          # Set permissions and finalize deployment
          ssh -p ${{ secrets.VPS_PORT }} root@${{ secrets.VPS_HOST }} "
            set -e
            
            # Make the Go application executable
            chmod +x ${{ secrets.VPS_ROOT_DIR }}/docker-manager
            
            # Set permissions for operation scripts
            mkdir -p ${{ secrets.VPS_ROOT_DIR }}/operations
            if [ -d \"${{ secrets.VPS_ROOT_DIR }}/operations\" ]; then
              echo \"Setting permissions for operation scripts...\"
              find ${{ secrets.VPS_ROOT_DIR }}/operations -type f -name "*.sh" -exec chmod +x {} \;
            fi
            
            echo \"Deployment completed successfully!\"
          "